dist: xenial
lang: c
script:
  - eval "${MATRIX_EVAL}" && ./autogen.sh && ./configure CC=$CC CXX=$CXX && make
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-8
          packages:
            - clang-8
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
